# Generated by Django 5.0.7 on 2025-02-25 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='grade_level',
            new_name='grade',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrollment_date',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='year',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('year', 'course'), name='unique_year_course'),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classroom.enrollmentyear'),
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ManyToManyField(related_name='enrollments', to='classroom.student'),
        ),
    ]
