# Generated by Django 5.0.7 on 2025-02-25 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_enrollmentyear_rename_grade_level_student_grade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'permissions': [('can_enroll_students', 'Can enroll students in courses')]},
        ),
    ]
